# Permalinks
permalink: pretty

# Setup
host: localhost
title: Rahul Shivaji Pawar
url: rahulshivajipawar.github.io

author:
    name: Rahul Shivaji Pawar
    email: rahulshivajipawar@gmail.com

future: true
permalink: "/:title/"


   

markdown: kramdown

gems:
    - jekyll-seo-tag
